### PR TITLE
Add launchable and developer name to apppdata

### PR DESCRIPTION
**Pull request by bbhtt**
See https://invent.kde.org/teams/flathub/issues/-/issues/28

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Review by travier — COMMENTED** [review]
LGTM. Has this been pushed upstream?

**Review by travier — APPROVED** [review]
LGTM. Has this been pushed upstream?

**Comment by bbhtt** [comment]
Upstream doesn't have appdata and also says unmaintained.

**Comment by travier** [comment]
Ah indeed!

**Pull request merged**
